/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Karyawan;
    import Koneksi.Db_Koneksi;
    import com.mysql.jdbc.PreparedStatement;
    import com.mysql.jdbc.Statement;
    import java.sql.ResultSet;
    import java.sql.SQLException;
    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;
    
/**
 *
 * @author selam
 */
public final class Form_Gaji extends javax.swing.JFrame {
private final DefaultTableModel model;
String Nip, Nama, Jabatan;
int Gapok, Transport, Gaber;



    /**
     * Creates new form Form_Gaji
     */
    public Form_Gaji() {
        initComponents();
        model = new DefaultTableModel();
        tblGaji.setModel(model);
        model.addColumn("Nip");       
        model.addColumn("Nama");
        model.addColumn("Jabatan");
        model.addColumn("Gaji Pokok");
        model.addColumn("Transport");
        model.addColumn("Gaji Bersih");
        
        getData();
     }    
   
    /**
     *
     * @param Gapok
     */

            

   
   
  

    

    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGaji = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cmboxJabatan = new javax.swing.JComboBox<>();
        txtGapok = new javax.swing.JTextField();
        txtTransport = new javax.swing.JTextField();
        txtGaber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        javax.swing.JButton btnKeluar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        tblGaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGaji.setGridColor(new java.awt.Color(0, 0, 0));
        tblGaji.setSelectionBackground(new java.awt.Color(0, 0, 204));
        tblGaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGajiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGaji);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 225, 638, 217);

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/Boss.png"))); // NOI18N
        jLabel1.setText("Data Gaji Karyawan PT Mukti Corp");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 638, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(29, 51, 70, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(29, 83, 40, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(29, 121, 80, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(336, 59, 50, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Transport");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(336, 90, 60, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gaji Bersih");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(336, 118, 70, 15);
        getContentPane().add(txtNip);
        txtNip.setBounds(112, 46, 197, 30);
        getContentPane().add(txtNama);
        txtNama.setBounds(112, 77, 197, 30);

        cmboxJabatan.setBackground(new java.awt.Color(51, 153, 255));
        cmboxJabatan.setForeground(new java.awt.Color(0, 51, 51));
        cmboxJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Asisten Manager", "Kepala HRD", "Staf Keuangan", "Karyawan", "Office Boy" }));
        cmboxJabatan.setToolTipText("");
        cmboxJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboxJabatanActionPerformed(evt);
            }
        });
        getContentPane().add(cmboxJabatan);
        cmboxJabatan.setBounds(109, 108, 200, 30);

        txtGapok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGapokActionPerformed(evt);
            }
        });
        getContentPane().add(txtGapok);
        txtGapok.setBounds(418, 46, 190, 30);
        getContentPane().add(txtTransport);
        txtTransport.setBounds(418, 77, 190, 30);
        getContentPane().add(txtGaber);
        txtGaber.setBounds(418, 108, 190, 30);

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/Save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(99, 156, 80, 51);

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/Undo.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(197, 156, 84, 51);

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/Update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(299, 156, 87, 51);

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/Delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(407, 156, 75, 51);

        btnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/Close.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKeluar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(509, 156, 72, 51);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAMBAR/20190112_165251 - Copy.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 660, 450);

        setSize(new java.awt.Dimension(674, 491));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtGapokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGapokActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtGapokActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        saveData();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmboxJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboxJabatanActionPerformed
        // TODO add your handling code here:
        loadtblGaji();
    }//GEN-LAST:event_cmboxJabatanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblGajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGajiMouseClicked
        // TODO add your handling code here:
        dataSelect();
    }//GEN-LAST:event_tblGajiMouseClicked

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_btnDeleteActionPerformed

   
   
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Form_Gaji().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmboxJabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGaji;
    private javax.swing.JTextField txtGaber;
    private javax.swing.JTextField txtGapok;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtTransport;
    // End of variables declaration//GEN-END:variables

    private void getData() {
         model.getDataVector().removeAllElements();
         model.fireTableDataChanged();
         
         try{
             
             Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
             String sql = "select * from tblGaji";
             ResultSet res = stat.executeQuery(sql);
             
             while(res.next()){                           
                 Object[] obj = new Object [6];
                 obj [0] = res.getString("Nip");
                 obj [1] = res.getString("Nama");
                 obj [2] = res.getString("Jabatan");
                 obj [3] = res.getString("Gapok");
                 obj [4] = res.getString("Transport");
                 obj [5] = res.getString("Gaber");
                 
                 model.addRow(obj);
             }
             }catch(SQLException err){
                 JOptionPane.showMessageDialog(null, err.getMessage());
             } 
         }  

    private void loadData() {
        Nip	 = txtNip.getText();
        Nama	 = txtNama.getText();
        Jabatan	 = (String) cmboxJabatan.getSelectedItem();
        int Gapok = Integer.parseInt(txtGapok.getText());
        Transport= Integer.parseInt(txtTransport.getText());
        Gaber	 = Integer.parseInt(txtGaber.getText());
    }

    private void saveData() {
       loadData();
try{
	Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
	String sql = "Insert into tblGaji (Nip, Nama, Jabatan, Gapok, Transport, Gaber)"
		+ "values ('"+ Nip +"', '"+ Nama +"', '"+ Jabatan +"', '"+ Gapok +"', '"+ Transport +"', '"+ Gaber +"')";
	PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);	
	p.executeUpdate();
	getData();
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan...");
	}catch(SQLException err){
		JOptionPane.showMessageDialog(null, err.getMessage());
	}
    }

    private void loadtblGaji() {
       Jabatan     =""+ cmboxJabatan.getSelectedItem();
       switch(Jabatan){
    case "Manager":
        Gapok	= 5000000;
    break;
    case "Asisten Manager":
        Gapok	= 4500000;
    break;
    case "Kepala HRD":
        Gapok	= 5000000;
    break;
    case "Staf Keuangan":
        Gapok	= 3500000;
    break;
    case "Karyawan":
        Gapok	= 3000000;
    break;
    case "Office Boy":
        Gapok	= 2500000;
    break;
}
Transport = (int) (Gapok * 0.1);
Gaber	  = (int) (Gapok + Transport);
txtGapok.setText(""+Gapok);
txtTransport.setText(""+Transport);
txtGaber.setText(""+Gaber);
    }

  
  
    /**
     *
     */
    public void Reset(){
Nip	= "";
Nama	= "";
Jabatan	= "";
    int Gapok = 0;
Transport= 0;
Gaber	= 0;
txtNip.setText(Nip);
txtNama.setText(Nama);
txtGapok.setText("");
txtTransport.setText("");
txtGaber.setText("");
}

    private void dataSelect() {
        
               int i = tblGaji.getSelectedRow();
	if (i ==-1){
	return;
}
txtNip.setText(""+model.getValueAt(i, 0));
txtNama.setText(""+model.getValueAt(i, 1));
cmboxJabatan.setSelectedItem(""+model.getValueAt(i, 2));
txtGapok.setText(""+model.getValueAt(i, 3));
txtTransport.setText(""+model.getValueAt(i, 4));
txtGaber.setText(""+model.getValueAt(i, 5));  
        
    }

    private void updateData() {
  loadData();
try{
	Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
	String sql = "Update tblGaji Set Nama	= '"+ Nama +"',"
				+ "Jabatan 	= '"+ Jabatan +"',"
				+ "Gapok 	= '"+ Gapok +"',"
				+ "Transport 	= '"+ Transport +"',"
				+ "Gaber 	= '"+ Gaber+"' Where Nip = '"+ Nip +"'";
        PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);	
	p.executeUpdate();
	getData();
	Reset();
	JOptionPane.showMessageDialog(null, "Update Berhasil...");
	}catch(SQLException err){
		JOptionPane.showMessageDialog(null, err.getMessage());
	}
    }

    private void deleteData() {
        	loadData();
	int pesan = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Menghapus Data"+ Nip +"?","Konfirmasi",JOptionPane.OK_CANCEL_OPTION);
	if (pesan == JOptionPane.OK_OPTION){
	try{
	Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
	String sql = "DELETE FROM tblgaji WHERE Nip = '"+ Nip +"'";
	PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);	
	p.executeUpdate();
	getData();
	Reset();
	JOptionPane.showMessageDialog(null, "Delete Berhasil");
	}catch(SQLException err){
		JOptionPane.showMessageDialog(null, err.getMessage());
	}
       } 
    }
}    

    
    
    
    
  
    

        
    









